AWSTemplateFormatVersion: '2010-09-09'
Description: Container repository for a native Kotlin Lambda application
Resources:
  Repository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      ImageTagMutability: IMMUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true
Outputs:
  RepositoryUri:
    Value: !GetAtt Repository.RepositoryUri
